algoritmo "semnome"

var
numeroA, numeroB, numeroC: real
calculo: real
inicio
Escreval("Insira um valor para 'A'")
leia(numeroA)
limpatela
Escreval("Insira um valor para 'B'")
leia(numeroB)
limpatela
Escreval("Insira um valor para 'C'")
leia(numeroC)
limpatela

calculo <- numeroA+numeroB
se(calculo<numeroC)entao
escreval("A soma dos números A e B é menor que C.")
senao
escreval("A soma dos números A e B é maior que C.")
fimse

// Seção de Comandos 
fimalgoritmo
