algoritmo "semnome"
var
numeroA, numeroB, numeroC:inteiro
inicio
escreval("Insira o valor de A")
leia(numeroA)
escreval("Insira o valor de B")
leia(numeroB)

se(numeroA=numeroB)entao
numeroC <- numeroA+numeroB
escreval(,numeroC," foi o valor da soma desses números")
senao
numeroC <- numeroA*numeroB
escreval(,numeroC," foi o valor da multiplicação desses números")
fimse
// Seção de Comandos 
fimalgoritmo
